apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-api-server
  labels:
    k8s-app: math-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: math-api-server
  template:
    metadata:
      name: math-api-server
      creationTimestamp: null
      labels:
        k8s-app: math-api-server
    spec:
      containers:
        - name: math-api-server
          image: machripe/math-api-server
          resources: {}
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst